version: "3"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres  # Add this line
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: postgres  # Optional: specify a default database
